# Generated by Django 4.0.5 on 2022-10-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomeSequence', models.TextField(max_length=999999999)),
            ],
        ),
    ]
